name: "Deploy NextJS VPS Hostinger"
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar git pull no servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /projects
            echo "PWD inicial:"
            pwd
            echo "Conteúdo de /projects:"
            ls -la /root/projects

            if [ ! -d "/root/projects/products-digital/.git" ]; then
                echo "Clonando repositório..."
                git clone https://github.com/jnerydesigner/products-digital /root/projects/products-digital
            else
                echo "Repositório já clonado"
            fi

            echo "Entrando na pasta do projeto"
            cd /root/projects/products-digital
            echo "PWD após cd:"
            pwd
            echo "Conteúdo da pasta do projeto:"
            ls -la

            echo "Executando git pull"
            git pull origin main

      - name: Instalando as dependencias
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/projects/seligadev
            yarn install

      # - name: Executar o Build No Servidor
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /root/projects/seligadev
      #       export DATABASE_URL=${{ secrets.DATABASE_URL }}
      #       export NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
      #       yarn build

      # - name: Executar o PM2 e Start No Servidor
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /root/projects/seligadev
      #       pm2 update seligadev || true
      #       pm2 start my-pm2-start.json --update-env || pm2 restart my-pm2-start.json
